#!/usr/bin/env python3
"""Prepare the user's SVG Repo emotions for the StackChan preview/firmware.

The source artwork has a shared yellow circular face.  This script removes the
white page rectangle and the three yellow/orange face layers while preserving
the dark facial features and colored accessories.  It also writes the final
PNG files into a compact C++ header after macOS Quick Look has rasterized them.
"""

from __future__ import annotations

import argparse
import re
import xml.etree.ElementTree as ET
from pathlib import Path


SOURCE_TO_NAME = {
    "angel-face-emoji-emoticon-emotion-face-smiley-svgrepo-com.svg": "omg",
    "angry-emoji-emoticon-emotion-expression-feeling-svgrepo-com.svg": "angry",
    "avatar-emoji-emoticon-emotion-expression-profile-svgrepo-com.svg": "wink",
    "crying-emoji-emoticon-emotion-expression-sad-svgrepo-com.svg": "sobbing",
    "crying-emoji-emoticon-emotion-sad-smiley-svgrepo-com.svg": "crying",
    "emoticon-emoticons-emotion-expression-face-svgrepo-com.svg": "pout",
    "emoticon-emotion-expression-face-feeling-svgrepo-com.svg": "whine",
    "emoticon-emotion-expression-face-glasses-svgrepo-com.svg": "cool",
    "emoticon-emotion-expression-face-happy-svgrepo-com.svg": "surprised",
    "emoticon-emotion-expression-face-silent-face-svgrepo-com.svg": "silent",
    "emoticon-emotion-expression-face-smiley-2-svgrepo-com.svg": "playful",
    "emoticon-emotion-expression-feeling-kiss-face-svgrepo-com.svg": "kiss",
    "emoticon-emotion-expression-frowningface-smile-svgrepo-com.svg": "awkward",
    "emoticon-emotion-expression-sad-face-smiley-2-svgrepo-com.svg": "worried",
    "emoticon-emotion-expression-shock-smiley-svgrepo-com.svg": "shocked",
    "emoticon-emotion-face-shy-smiley-svgrepo-com.svg": "shy",
    "emoticon-emotion-face-smiley-think-svgrepo-com.svg": "thinking",
}

FACE_COLORS = {"#ffc500", "#ff9f1e", "#ffe059"}
MOTIONS = {
    "omg": "Float",
    "angry": "Shake",
    "wink": "Bob",
    "sobbing": "Tear",
    "crying": "Tear",
    "pout": "Bob",
    "whine": "Bob",
    "cool": "Float",
    "surprised": "Bob",
    "silent": "Still",
    "playful": "Bob",
    "kiss": "Float",
    "awkward": "Bob",
    "worried": "Bob",
    "shocked": "Shake",
    "shy": "Float",
    "thinking": "Float",
}
EFFECTS = {
    "wink": "Wink",
    "kiss": "Kiss",
}

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def class_colors(root: ET.Element) -> dict[str, str]:
    result: dict[str, str] = {}
    for style in root.findall(f".//{{{SVG_NS}}}style"):
        for name, color in re.findall(
            r"\.([\w-]+)\s*\{[^}]*fill\s*:\s*(#[0-9a-fA-F]{6})", style.text or ""
        ):
            result[name] = color.lower()
    return result


def is_page_rect(element: ET.Element) -> bool:
    return (
        element.tag == f"{{{SVG_NS}}}rect"
        and float(element.get("width", "0")) >= 2000
        and float(element.get("height", "0")) >= 2000
    )


def strip_face(source: Path, destination: Path, name: str) -> None:
    tree = ET.parse(source)
    root = tree.getroot()
    colors = class_colors(root)

    for parent in root.iter():
        for child in list(parent):
            color = colors.get(child.get("class", ""), "")
            if is_page_rect(child) or color in FACE_COLORS:
                parent.remove(child)

    if name == "omg":
        # The original halo was intentionally wider than the yellow face. With
        # the circle removed it dominates the screen, so reduce it around its
        # own center while leaving the eyes and smile untouched.
        for element in root.iter():
            if colors.get(element.get("class", ""), "") == "#4795ff":
                previous = element.get("transform", "")
                shrink = "translate(1038.6 566.1) scale(.68) translate(-1038.6 -566.1)"
                element.set("transform", f"{shrink} {previous}".strip())

    # Preserve the source artwork's original x/y scale and center. Cropping the
    # square page to 4:3 removes only unused top/bottom space, so eye spacing and
    # eye-to-mouth distance remain the same as in the downloaded expression.
    root.set("width", "320")
    root.set("height", "240")
    root.set("viewBox", "0 256.25 2050 1537.5")
    destination.parent.mkdir(parents=True, exist_ok=True)
    tree.write(destination, encoding="utf-8", xml_declaration=True)


def write_header(png_dir: Path, destination: Path) -> None:
    lines = [
        "// Generated by generate_emotion_assets.py. Do not edit by hand.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace stackchan_emotions {",
        "enum class Motion : uint8_t { Still, Bob, Float, Shake, Tear };",
        "enum class Effect : uint8_t { None, Wink, Kiss };",
        "struct Asset {",
        "  const char* name;",
        "  const uint8_t* data;",
        "  size_t size;",
        "  Motion motion;",
        "  Effect effect;",
        "};",
        "",
    ]

    ordered_names = list(SOURCE_TO_NAME.values())
    for name in ordered_names:
        data = (png_dir / f"{name}.png").read_bytes()
        lines.append(f"static const uint8_t {name}_png[] = {{")
        for offset in range(0, len(data), 12):
            chunk = data[offset : offset + 12]
            lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
        lines.append("};")
        lines.append("")

    lines.append("static const Asset ASSETS[] = {")
    for name in ordered_names:
        lines.append(
            f'  {{"{name}", {name}_png, sizeof({name}_png), Motion::{MOTIONS[name]}, '
            f'Effect::{EFFECTS.get(name, "None")}}},'
        )
    lines.extend(
        [
            "};",
            "static constexpr size_t ASSET_COUNT = sizeof(ASSETS) / sizeof(ASSETS[0]);",
            "}  // namespace stackchan_emotions",
            "",
        ]
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare = subparsers.add_parser("prepare")
    prepare.add_argument("source_dir", type=Path)
    prepare.add_argument("svg_dir", type=Path)

    header = subparsers.add_parser("header")
    header.add_argument("png_dir", type=Path)
    header.add_argument("destination", type=Path)

    args = parser.parse_args()
    if args.command == "prepare":
        for filename, name in SOURCE_TO_NAME.items():
            strip_face(args.source_dir / filename, args.svg_dir / f"{name}.svg", name)
    else:
        write_header(args.png_dir, args.destination)


if __name__ == "__main__":
    main()
