[platformio]
default_envs = native

[env:native]
platform = native
build_type = debug
lib_extra_dirs = /Users/gongxiyue/Documents/Arduino/libraries
build_flags =
  -O0
  -xc++
  -std=c++14
  -lSDL2
  -I/opt/homebrew/include/SDL2
  -L/opt/homebrew/lib
